[package]
name = "rust_sim"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_sim"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module"] }
rand = "0.8"
rand_distr = "0.4"
